name: build-mac

on:
  workflow_dispatch: {}

jobs:
  mac-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mvp
          python-version: 3.9
          auto-update-conda: true

      - name: Create mac Python env and pack
        shell: bash -l {0}
        run: |
          # Install core scientific packages and system libraries from conda-forge
          conda install -c conda-forge "libblas=*=*openblas" "liblapack=*=*openblas" numpy scipy xz liblzma openblas -y
          # Install numpy with specific BLAS/LAPACK configuration
          conda install -c conda-forge numpy scipy --no-deps -y
          # Ensure all dependencies are properly linked
          conda list | grep -E "numpy|scipy|openblas|blas|lapack"
          
          # Install remaining requirements
          pip install -r backend/requirements.txt
          
          # Install PyInstaller and build the standalone backend executable
          conda install -y pyinstaller
          pyinstaller backend/main.py --name backend_executable --onefile --noconfirm
          
          # Add execute permissions to the backend executable
          chmod +x dist/backend_executable
          
          # Pack environment with all dependencies
          conda install -y conda-pack
          conda pack -n mvp -o mvp-env.tar.gz
          
          # Extract and prepare environment
          mkdir -p desktop/resources/python-env
          tar -xzf mvp-env.tar.gz -C desktop/resources/python-env
          
          # Fix permissions and paths
          chmod +x desktop/resources/python-env/bin/*
          cd desktop/resources/python-env
          ./bin/conda-unpack
          
          # Verify numpy and its dependencies
          ./bin/python -c "
          import numpy as np
          import os
          print('NumPy version:', np.__version__)
          print('NumPy location:', np.__file__)
          print('OpenBLAS location:', [f for f in os.listdir('./lib') if 'openblas' in f.lower()])
          "

      - name: Prepare app resources
        run: |
          # Create the destination directories
          mkdir -p desktop/resources/backend
          mkdir -p desktop/resources/frontend
          
          # Move the PyInstaller executable
          mv dist/backend_executable desktop/resources/backend/
          
          # Copy frontend files
          cp -R frontend/* desktop/resources/frontend/

      - name: Inject Secrets into Electron App
        shell: bash
        run: |
          # Use sed to replace placeholders in main.js with actual secrets
          # Note the use of different delimiters for sed to handle special characters in secrets
          sed -i.bak "s|YOUR_CLIENT_ID_PLACEHOLDER|${{ secrets.CLIENT_ID }}|g" "desktop/main.js"
          sed -i.bak "s|YOUR_CLIENT_SECRET_PLACEHOLDER|${{ secrets.CLIENT_SECRET }}|g" "desktop/main.js"
          sed -i.bak "s|'false'|'${{ vars.USE_MOCK_SERVER || 'false' }}'|g" "desktop/main.js"
          sed -i.bak "s|'2'|'${{ vars.LOG_VERBOSE || '2' }}'|g" "desktop/main.js"


      - name: Install desktop deps
        working-directory: desktop
        run: npm ci || npm i

      - name: Build mac artifact (arm64, unsigned)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
          BUILD_BLOCKMAP: 'false'
        working-directory: desktop
        run: npx electron-builder --mac --arm64 --publish=never -c.compression=store

      - name: Upload artifact (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: mac-build-arm64
          path: desktop/dist/*

  mac-x64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: mvp
          python-version: 3.9
          auto-update-conda: true

      - name: Create mac Python env and pack (x64)
        shell: bash -l {0}
        run: |
          # Install core scientific packages and system libraries from conda-forge
          conda install -c conda-forge "libblas=*=*openblas" "liblapack=*=*openblas" numpy scipy xz liblzma openblas -y
          # Install numpy with specific BLAS/LAPACK configuration
          conda install -c conda-forge numpy scipy --no-deps -y
          # Ensure all dependencies are properly linked
          conda list | grep -E "numpy|scipy|openblas|blas|lapack"
          
          # Install remaining requirements
          pip install -r backend/requirements.txt
          
          # Install PyInstaller and build the standalone backend executable (x64)
          conda install -y pyinstaller
          pyinstaller backend/main.py --name backend_executable --onefile --noconfirm
          
          # Add execute permissions to the backend executable
          chmod +x dist/backend_executable
          
          # Pack environment with all dependencies
          conda install -y conda-pack
          conda pack -n mvp -o mvp-env.tar.gz
          
          # Extract and prepare environment
          mkdir -p desktop/resources/python-env
          tar -xzf mvp-env.tar.gz -C desktop/resources/python-env
          
          # Fix permissions and paths
          chmod +x desktop/resources/python-env/bin/*
          cd desktop/resources/python-env
          ./bin/conda-unpack
          
          # Verify numpy and its dependencies
          ./bin/python -c "
          import numpy as np
          import os
          print('NumPy version:', np.__version__)
          print('NumPy location:', np.__file__)
          print('OpenBLAS location:', [f for f in os.listdir('./lib') if 'openblas' in f.lower()])
          "

      - name: Prepare app resources
        run: |
          # Create the destination directories
          mkdir -p desktop/resources/backend
          mkdir -p desktop/resources/frontend

          # Move the PyInstaller executable
          mv dist/backend_executable desktop/resources/backend/
          
          # Copy frontend files
          cp -R frontend/* desktop/resources/frontend/

      - name: Inject Secrets into Electron App (x64)
        shell: bash
        run: |
          # Use sed to replace placeholders in main.js with actual secrets
          sed -i.bak "s|YOUR_CLIENT_ID_PLACEHOLDER|${{ secrets.CLIENT_ID }}|g" "desktop/main.js"
          sed -i.bak "s|YOUR_CLIENT_SECRET_PLACEHOLDER|${{ secrets.CLIENT_SECRET }}|g" "desktop/main.js"
          sed -i.bak "s|'true'|'${{ vars.USE_MOCK_SERVER || 'false' }}'|g" "desktop/main.js"
          sed -i.bak "s|'2'|'${{ vars.LOG_VERBOSE || '2' }}'|g" "desktop/main.js"


      - name: Install desktop deps
        working-directory: desktop
        run: npm ci || npm i

      - name: Build mac artifact (x64, unsigned)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
          BUILD_BLOCKMAP: 'false'
        working-directory: desktop
        run: npx electron-builder --mac --x64 --publish=never -c.compression=store

      - name: Upload artifact (x64)
        uses: actions/upload-artifact@v4
        with:
          name: mac-build-x64
          path: desktop/dist/*


